### ISSUE TITLE
Allow sorting attributes/namespace declarations (for diffing)

### ISSUE THREAD

**Issue by phirsch** [weetmuts/xmq#10]
XML documents with identical structure and content, but different ordering of attributes (e.g. xmlns declarations) for an element, show differences, e.g. in xmq-meld. It would be great to have a choice to ignore/suppress these differences (since attribute order is insignificant according to the XML spec).

**Comment by weetmuts** [comment]
Good idea! I added --sort-attributes so now you can write:
xmq-meld --sort-attributes alfa.xml beta.xml

Please test!

**Comment by phirsch** [comment]
A (very brief) test with the file pair I used yesterday (slide files within a PPTX file) worked beautifully: with `--sort-attributes` `xmq-meld` now considers them identical. Thanks a lot!

NB: Some open source software (authors, I should probably say) never cease(s) to amaze me! Sometimes, you just submit an idea or bug report in a hurry, only to find that the world has become a better place the very next day — you just made my day!
